version: '3.9'

name: informationssysteme-a05

services:
    neo4j:
        image: neo4j:5
        ports:
            - "7474:7474"
            - "7687:7687"
        volumes:
            - neo4j-data:/data
            - neo4j-plugins:/plugins
            - ./import:/import
        environment:
            - NEO4J_AUTH=none
            - NEO4J_apoc_import_file_enabled=true
            - NEO4J_apoc_export_file_enabled=true
            - NEO4J_PLUGINS=["apoc"]
    mongo:
        image: mongo
        ports:
            - "27017:27017"
        volumes:
            - mongo_data:/data/db
    mongo-express:
        image: mongo-express
        hostname: mongo-express
        depends_on:
            - mongo
        ports:
            - "8081:8081"

volumes:
    neo4j-data:
    neo4j-plugins:
    mongo_data:
