version: '3.9'

name: informationssysteme-a05

services:
    neo4j:
        image: neo4j:5.3.0-community
        ports:
            - "40433:7474"
            - "7687:7687"
        volumes:
            - neo4j-data:/data
            # Use the local plugins folder to load custom downloaded plugins (APOC extended)
            - ./plugins:/plugins
            - ./import:/import
        environment:
            - NEO4J_AUTH=none
            - NEO4J_apoc_import_file_enabled=true
            - NEO4J_apoc_export_file_enabled=true
            - NEO4J_apoc_import_file_use__neo4j__config=true
    mongo:
        image: mongo
        ports:
            - "27017:27017"
        volumes:
            - mongo_data:/data/db
    mongo-express:
        image: mongo-express
        hostname: mongo-express
        depends_on:
            - mongo
        ports:
            - "40434:8081"

volumes:
    neo4j-data:
    mongo_data:
