version: '3.8'

services:
    neo4j:
        image: neo4j
        restart: always
        ports:
            - "7474:7474"
            - "7687:7687"
        volumes:
            - neo4j-data:/data
        environment:
            - NEO4J_AUTH=none

volumes:
    neo4j-data:
