version: '3.1'

services:
    neo4j:
        image: neo4j:4.4.0
        ports:
            - "7474:7474"
            - "7687:7687"
        volumes:
            - neo4j-data:/data
            - neo4j-plugins:/plugins
            - ./import:/import
        environment:
            - NEO4J_AUTH=none
            - NEO4J_apoc_import_file_enabled=true
            - NEO4J_apoc_export_file_enabled=true
            - NEO4JLABS_PLUGINS=["apoc"]

volumes:
    neo4j-data:
    neo4j-plugins:
